import JSZip from "jszip";
import type { SiteModel } from "@/lib/models/site-model";
import {
  renderSiteCss,
  renderSiteHtml,
  renderSiteJs,
} from "@/lib/generation/site-renderer";

async function fetchImageAsBlob(url: string): Promise<Blob | null> {
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(10000) });
    if (!res.ok) return null;
    return await res.blob();
  } catch {
    return null;
  }
}

function extensionFromUrl(url: string): string {
  try {
    const pathname = new URL(url).pathname;
    const ext = pathname.split(".").pop()?.split("?")[0];
    if (ext && ["jpg", "jpeg", "png", "webp", "gif"].includes(ext.toLowerCase())) {
      return ext;
    }
  } catch {
    /* ignore */
  }
  return "jpg";
}

export async function buildExportZip(site: SiteModel): Promise<Blob> {
  const zip = new JSZip();
  const folder = zip.folder(`${site.slug}-demo`);
  if (!folder) throw new Error("Failed to create zip folder");

  const imageMap = new Map<string, string>();
  const allImages = [
    site.hero.image,
    ...site.gallery.images,
  ].filter(Boolean);

  let imgIndex = 0;
  for (const url of allImages) {
    if (imageMap.has(url)) continue;
    const blob = await fetchImageAsBlob(url);
    if (blob) {
      const ext = extensionFromUrl(url);
      const filename = `assets/image-${imgIndex}.${ext}`;
      folder.file(filename, blob);
      imageMap.set(url, filename);
      imgIndex++;
    }
  }

  const siteForExport: SiteModel = JSON.parse(JSON.stringify(site));
  siteForExport.hero.image = imageMap.get(site.hero.image) || site.hero.image;
  siteForExport.gallery.images = site.gallery.images.map(
    (img) => imageMap.get(img) || img
  );

  folder.file("index.html", renderSiteHtml(siteForExport, { editMode: false }));
  folder.file("css/styles.css", renderSiteCss(siteForExport));
  folder.file("js/main.js", renderSiteJs());

  folder.file(
    "README.txt",
    `${site.businessName} — Demo Site
============================

Quick Edit Guide:
- index.html: Main page (or edit css/styles.css for styling)
- css/styles.css: All styles and design tokens
- js/main.js: Scroll animations and mobile nav
- assets/: Downloaded business photos

To view locally:
  Open index.html in your browser

To deploy:
  Upload the entire folder to any static host (Netlify, Vercel, Cloudflare Pages)

Design tokens (edit in css/styles.css :root):
  --color-primary, --color-accent, --color-bg, etc.

Generated by Demo Builder V2
`
  );

  return zip.generateAsync({ type: "blob" });
}
